name = "OneYWoPor"
version = "0.3.4"
defaultTargets = ["Por"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.33.1"

[[lean_lib]]
name = "Por"

[[lean_lib]]
name = "ZeroY"

[[lean_lib]]
name = "OneY"
